[features]
seeds = false
skip-lint = false
[programs.devnet]
ticketcoin_contract = "69YpUBXmA97Lhjy21Wm4chkzkbh4SjwAFaHfNnNr8iJv"

[programs.localnet]
ticketcoin_contract = "69YpUBXmA97Lhjy21Wm4chkzkbh4SjwAFaHfNnNr8iJv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.solana/wallets/devnet-wallet.json"
test = "~/.solana/wallets/devnet-wallet2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
